[package]
name = "board"
version = "0.1.0"
edition = "2024"

[dependencies]
enum_ext = "0.3.0"
bitfield-struct = "0.10"
bit-iter = "1.3.1"
arrayvec = "0.7.6"

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "perft"
harness = false